export const sampleData = [
  "React - A JavaScript library for building user interfaces",
  "JavaScript - A versatile programming language for web development",
  "TypeScript - A typed superset of JavaScript that compiles to plain JavaScript",
  "HTML - The standard markup language for creating web pages",
  "CSS - A style sheet language for designing the layout and appearance of web pages",
  "Node.js - A JavaScript runtime built on Chrome's V8 JavaScript engine",
  "Express.js - A minimal and flexible Node.js web application framework",
  "MongoDB - A NoSQL database program using JSON-like documents with optional schemas",
  "Redux - A predictable state container for JavaScript apps",
  "Next.js - A React framework for server-side rendering and building full-stack applications",
  "Tailwind CSS - A utility-first CSS framework for rapid UI development",
  "Chakra UI - A modular and accessible component library for React",
  "Firebase - A platform developed by Google for creating mobile and web applications",
  "GraphQL - A query language for your API to retrieve only the data you need",
  "Docker - A platform for developing, shipping, and running applications inside containers",
  "Kubernetes - An open-source system for automating deployment, scaling, and management of containerized applications",
  "AWS - Amazon Web Services, a cloud computing platform offering a variety of services",
  "Git - A distributed version control system to track changes in source code",
  "GitHub - A web-based hosting service for version control using Git",
  "REST API - An architectural style for designing networked applications",
];
